/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.AttendanceDevice;
import com.sunsetbeach.model.AttendanceDeviceInput;
import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.OkTrue;
import com.sunsetbeach.model.ValidationError;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
public interface AttendanceDevicesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /attendance/devices : Register a fingerprint terminal
     * Requires MANAGER or above. &#x60;serial&#x60; must be unique - registering the same physical device twice is rejected with 409.
     *
     * @param attendanceDeviceInput  (required)
     * @return Device registered. (status code 201)
     *         or Body failed validation. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     *         or A device with this serial is already registered. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/attendance/devices",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<AttendanceDevice> createAttendanceDevice(
         @Valid @RequestBody AttendanceDeviceInput attendanceDeviceInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"lastSeenAt\" : \"2000-01-23T04:56:07.000+00:00\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"address\" : \"address\", \"serial\" : \"serial\", \"port\" : 0, \"timezone\" : \"timezone\", \"name\" : \"name\", \"active\" : true, \"id\" : \"id\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /attendance/devices/{id} : Delete a fingerprint terminal
     * Requires MANAGER or above. A device that has ever produced a punch (has &#x60;AttendancePunch&#x60; rows) can&#39;t be deleted - deactivate it (&#x60;active&#x3D;false&#x60;) instead, the same convention as &#x60;DELETE /printers/{id}&#x60;. 
     *
     * @param id  (required)
     * @return Deleted. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     *         or Device not found. (status code 404)
     *         or This device has recorded punches and can&#39;t be deleted. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/attendance/devices/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<OkTrue> deleteAttendanceDevice(
         @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ok\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /attendance/devices : List fingerprint terminals
     * Requires MANAGER or above. Every registered device, active or not.
     *
     * @return All devices. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/attendance/devices",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<AttendanceDevice>> listAttendanceDevices(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"lastSeenAt\" : \"2000-01-23T04:56:07.000+00:00\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"address\" : \"address\", \"serial\" : \"serial\", \"port\" : 0, \"timezone\" : \"timezone\", \"name\" : \"name\", \"active\" : true, \"id\" : \"id\" }, { \"lastSeenAt\" : \"2000-01-23T04:56:07.000+00:00\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"address\" : \"address\", \"serial\" : \"serial\", \"port\" : 0, \"timezone\" : \"timezone\", \"name\" : \"name\", \"active\" : true, \"id\" : \"id\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /attendance/devices/{id} : Update a fingerprint terminal
     * Requires MANAGER or above. Full replacement of all &#x60;AttendanceDeviceInput&#x60; fields - no partial update, same convention as &#x60;PrinterInput&#x60;.
     *
     * @param id  (required)
     * @param attendanceDeviceInput  (required)
     * @return Updated device. (status code 200)
     *         or Body failed validation. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     *         or Device not found. (status code 404)
     *         or Another device already has this serial. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/attendance/devices/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<AttendanceDevice> updateAttendanceDevice(
         @PathVariable("id") String id,
         @Valid @RequestBody AttendanceDeviceInput attendanceDeviceInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"lastSeenAt\" : \"2000-01-23T04:56:07.000+00:00\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"address\" : \"address\", \"serial\" : \"serial\", \"port\" : 0, \"timezone\" : \"timezone\", \"name\" : \"name\", \"active\" : true, \"id\" : \"id\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
