/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.AuditAction;
import com.sunsetbeach.model.AuditEntityType;
import com.sunsetbeach.model.AuditLogPage;
import com.sunsetbeach.model.ErrorMessage;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-30T12:20:31.062819400+03:00[Europe/Moscow]", comments = "Generator version: 7.10.0")
@Validated
public interface AuditLogApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /audit-log : Search the audit log
     * Requires MANAGER or above. Every filter is optional and combines with AND; with none given, returns the most recent entries across the whole system, newest first. &#x60;entityType&#x60;+&#x60;entityId&#x60; together is how a specific booking&#39;s or order&#39;s own history is found (e.g. the booking detail page&#39;s History section calls this with &#x60;entityType&#x3D;Booking&amp;entityId&#x3D;{id}&#x60;) - &#x60;entityId&#x60; alone without &#x60;entityType&#x60; is rejected, since the same id string has no meaning without knowing which kind of record it names. 
     *
     * @param actorEmail Case-insensitive substring match against the actor&#39;s email as it was recorded at the time of the action (not a live lookup against the current &#x60;User&#x60; table - see &#x60;AuditLogEntry.actorEmail&#x60;). Filtering by email rather than user id avoids forcing a MANAGER caller through the ADMIN-only &#x60;GET /users&#x60; just to find an id to filter by.  (optional)
     * @param action  (optional)
     * @param entityType  (optional)
     * @param entityId Requires &#x60;entityType&#x60; to also be given. (optional)
     * @param from Inclusive start date (by &#x60;createdAt&#x60;). (optional)
     * @param to Inclusive end date (by &#x60;createdAt&#x60;). (optional)
     * @param page  (optional, default to 0)
     * @param pageSize  (optional, default to 50)
     * @return A page of matching entries, newest first. (status code 200)
     *         or &#x60;entityId&#x60; given without &#x60;entityType&#x60;, an invalid date, or &#x60;from&#x60; after &#x60;to&#x60;. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/audit-log",
        produces = { "application/json" }
    )
    
    default ResponseEntity<AuditLogPage> listAuditLog(
         @Valid @RequestParam(value = "actorEmail", required = false) String actorEmail,
         @Valid @RequestParam(value = "action", required = false) AuditAction action,
         @Valid @RequestParam(value = "entityType", required = false) AuditEntityType entityType,
         @Valid @RequestParam(value = "entityId", required = false) String entityId,
        @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$")  @Valid @RequestParam(value = "from", required = false) String from,
        @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$")  @Valid @RequestParam(value = "to", required = false) String to,
        @Min(0)  @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(1) @Max(200)  @Valid @RequestParam(value = "pageSize", required = false, defaultValue = "50") Integer pageSize
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"pageSize\" : 6, \"page\" : 0, \"totalCount\" : 1, \"items\" : [ { \"summary\" : \"summary\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"actorUserId\" : \"actorUserId\", \"entityType\" : \"Booking\", \"actorRole\" : \"ADMIN\", \"actorEmail\" : \"actorEmail\", \"action\" : \"BOOKING_CREATED\", \"entityId\" : \"entityId\", \"id\" : \"id\" }, { \"summary\" : \"summary\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"actorUserId\" : \"actorUserId\", \"entityType\" : \"Booking\", \"actorRole\" : \"ADMIN\", \"actorEmail\" : \"actorEmail\", \"action\" : \"BOOKING_CREATED\", \"entityId\" : \"entityId\", \"id\" : \"id\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
