/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-17T16:01:20.967720600+03:00[Europe/Moscow]", comments = "Generator version: 7.10.0")
@Validated
public interface AuthApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /auth/{nextauth} : NextAuth.js GET endpoints (session, csrf, providers, signin/signout pages, oauth callbacks)
     * Delegated entirely to &#x60;NextAuth(authOptions)&#x60; from &#x60;next-auth&#x60; (Credentials provider, JWT session strategy). Request/response shapes are whatever the installed &#x60;next-auth&#x60; v4 version defines for each sub-route and are not reproduced here. 
     *
     * @param nextauth Catch-all segment(s) consumed by NextAuth.js (e.g. &#x60;session&#x60;, &#x60;csrf&#x60;, &#x60;providers&#x60;, &#x60;callback/credentials&#x60;, &#x60;signin&#x60;, &#x60;signout&#x60;).  (required)
     * @return Response shape depends on the NextAuth.js sub-route requested. (status code 200)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/auth/{nextauth}"
    )
    
    default ResponseEntity<Void> nextAuthGet(
         @PathVariable("nextauth") String nextauth
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /auth/{nextauth} : NextAuth.js POST endpoints (signin/signout/callback)
     * Delegated entirely to &#x60;NextAuth(authOptions)&#x60;. The &#x60;callback/credentials&#x60; sub-route is what &#x60;/admin/login&#x60; submits to; it validates &#x60;email&#x60;/&#x60;password&#x60; against &#x60;User.passwordHash&#x60; (bcrypt) and, on success, sets the JWT session cookie described in &#x60;sessionAuth&#x60;. 
     *
     * @param nextauth Catch-all segment(s) consumed by NextAuth.js (e.g. &#x60;session&#x60;, &#x60;csrf&#x60;, &#x60;providers&#x60;, &#x60;callback/credentials&#x60;, &#x60;signin&#x60;, &#x60;signout&#x60;).  (required)
     * @return Response shape depends on the NextAuth.js sub-route requested. (status code 200)
     *         or Redirect (e.g. after signin/signout). (status code 302)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/{nextauth}",
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    default ResponseEntity<Void> nextAuthPost(
         @PathVariable("nextauth") String nextauth
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
