/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.AvailabilityRangeInput;
import com.sunsetbeach.model.AvailabilityResponse;
import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.OkUpdated;
import com.sunsetbeach.model.SetRoomPricing400Response;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-17T16:01:20.967720600+03:00[Europe/Moscow]", comments = "Generator version: 7.10.0")
@Validated
public interface AvailabilityApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /availability/{roomId} : Get day-by-day availability for a room for a given month
     * Requires any authenticated staff session (ADMIN or MANAGER). A day is blocked if it is covered by a non-CANCELLED booking (&#x60;source: \&quot;booking\&quot;&#x60;) or by a manual &#x60;Availability&#x60; block (&#x60;source: \&quot;manual\&quot;&#x60;). 
     *
     * @param roomId  (required)
     * @param month Month key &#x60;YYYY-MM&#x60;. Defaults to the current UTC month. (optional)
     * @return Availability for every day of the month. (status code 200)
     *         or No valid session cookie. (status code 401)
     *         or Room not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/availability/{roomId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<AvailabilityResponse> getRoomAvailability(
         @PathVariable("roomId") String roomId,
        @Pattern(regexp = "^\\d{4}-\\d{2}$")  @Valid @RequestParam(value = "month", required = false) String month
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"days\" : [ { \"date\" : \"date\", \"isBlocked\" : true, \"source\" : \"booking\" }, { \"date\" : \"date\", \"isBlocked\" : true, \"source\" : \"booking\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /availability/{roomId} : Set a manual block/unblock for a date range
     * Requires any authenticated staff session (ADMIN or MANAGER). Upserts one &#x60;Availability&#x60; row per day in &#x60;[from, to]&#x60; (inclusive). Rejects ranges longer than 366 days. This never touches bookings — it only controls the manual-block layer. 
     *
     * @param roomId  (required)
     * @param availabilityRangeInput  (required)
     * @return Number of days upserted. (status code 200)
     *         or Body failed &#x60;availabilityRangeSchema&#x60; validation, or the range exceeds 366 days. (status code 400)
     *         or No valid session cookie. (status code 401)
     *         or Room not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/availability/{roomId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<OkUpdated> setRoomAvailability(
         @PathVariable("roomId") String roomId,
         @Valid @RequestBody AvailabilityRangeInput availabilityRangeInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ok\" : true, \"updated\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
