/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.GuestAccount;
import com.sunsetbeach.model.GuestAccountAuthResponse;
import com.sunsetbeach.model.GuestBookingView;
import com.sunsetbeach.model.GuestPasswordChangeInput;
import com.sunsetbeach.model.ValidationError;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
public interface GuestAccountApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PATCH /guest/password : Change your own guest account password
     * Same shape as &#x60;Auth.changeOwnPassword&#x60;: verifies &#x60;currentPassword&#x60; against this account&#39;s own &#x60;passwordHash&#x60;, then bumps &#x60;tokenVersion&#x60; - every other guest token already issued to this account is rejected on its next request. The response carries a fresh token so this session keeps working without a re-login. 
     *
     * @param guestPasswordChangeInput  (required)
     * @return Password changed - a fresh token is returned. (status code 200)
     *         or Body failed validation. (status code 400)
     *         or Missing/invalid guest token, or &#x60;currentPassword&#x60; is incorrect. (status code 401)
     */
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/guest/password",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<GuestAccountAuthResponse> changeGuestAccountPassword(
         @Valid @RequestBody GuestPasswordChangeInput guestPasswordChangeInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"account\" : { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"emailVerifiedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"id\" : \"id\", \"email\" : \"email\" }, \"token\" : \"token\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /guest/me : Get the currently authenticated guest account
     * Requires a valid guest &#x60;Authorization: Bearer&#x60; JWT (see &#x60;GuestAccountAuth&#x60;).
     *
     * @return The authenticated guest account. (status code 200)
     *         or Missing/invalid/expired guest token. (status code 401)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/guest/me",
        produces = { "application/json" }
    )
    
    default ResponseEntity<GuestAccount> getCurrentGuestAccount(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"emailVerifiedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"name\" : \"name\", \"id\" : \"id\", \"email\" : \"email\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /guest/bookings : This guest&#39;s booking history
     * Every &#x60;Booking&#x60; whose &#x60;guestEmail&#x60; matches this account&#39;s own verified email, case-insensitively, newest (&#x60;createdAt&#x60;) first - past, current, and future stays alike. Computed fresh on every call, not a stored link (see the &#x60;GuestAccount&#x60; tag&#39;s own description) - deliberately narrow, guest-facing &#x60;GuestBookingView&#x60;, never the staff &#x60;Booking&#x60; shape (no &#x60;paymentNote&#x60;, &#x60;source&#x60;, &#x60;guestId&#x60;/&#x60;guest&#x60;, &#x60;roomUnitId&#x60;/&#x60;roomUnit&#x60;, occupancy timestamps, or anything else staff-internal). 
     *
     * @return This guest&#39;s bookings, newest first. Empty array if none. (status code 200)
     *         or Missing/invalid/expired guest token. (status code 401)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/guest/bookings",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<GuestBookingView>> listCurrentGuestBookings(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"checkIn\" : \"checkIn\", \"totalPrice\" : \"totalPrice\", \"id\" : \"id\", \"checkOut\" : \"checkOut\", \"roomName\" : \"roomName\", \"status\" : \"NEW\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"checkIn\" : \"checkIn\", \"totalPrice\" : \"totalPrice\", \"id\" : \"id\", \"checkOut\" : \"checkOut\", \"roomName\" : \"roomName\", \"status\" : \"NEW\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
