/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.NightAudit;
import com.sunsetbeach.model.NightAuditCloseInput;
import com.sunsetbeach.model.NightAuditClosure;
import com.sunsetbeach.model.ValidationError;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
public interface NightAuditApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /night-audit/close : Record that a date was reviewed and closed
     * Requires CASHIER or above, same as the checklist. Writes one &#x60;NightAuditClosure&#x60; - a receipt that a person reviewed this date, nothing more. It does not require &#x60;missedArrivals&#x60;/&#x60;missedDepartures&#x60; to be empty, and closing a date prevents nothing afterwards: payments, folio settlements and booking edits dated into it stay allowed. One closure per date - a second attempt is a 409, never an overwrite. Recorded in the audit log (&#x60;NIGHT_AUDIT_CLOSED&#x60;). 
     *
     * @param nightAuditCloseInput  (required)
     * @return The closure just recorded. (status code 200)
     *         or &#x60;date&#x60; missing or not a valid date. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or This date is already closed. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/night-audit/close",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<NightAuditClosure> closeNightAudit(
         @Valid @RequestBody NightAuditCloseInput nightAuditCloseInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"date\", \"notes\" : \"notes\", \"closedByName\" : \"closedByName\", \"closedByUserId\" : \"closedByUserId\", \"closedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /night-audit : The night-audit checklist for one hotel-local date
     * Requires CASHIER or above - routine front-desk work done every day, unlike the strategic &#x60;/reports/_*&#x60; (MANAGER+). Read-only; nothing here acts on the bookings it lists.  **&#x60;missedArrivals&#x60;**: bookings whose &#x60;occupancyStatus&#x60; is &#x60;EXPECTED&#x60;, &#x60;status&#x60; is not &#x60;CANCELLED&#x60;, and &#x60;checkIn&#x60; is on or before &#x60;date&#x60;. On or before, not only equal: a missed arrival from an earlier day that nobody resolved stays on the list until someone checks the guest in or marks them no-show (&#x60;POST /bookings/{id}/no-show&#x60;).  **&#x60;missedDepartures&#x60;**: bookings whose &#x60;occupancyStatus&#x60; is &#x60;CHECKED_IN&#x60; and &#x60;checkOut&#x60; is on or before &#x60;date&#x60;.  Both lists reflect the bookings&#39; state *now*, not as it was on &#x60;date&#x60; - reviewing a past date shows what is still unresolved with a date on or before it, not a historical snapshot.  **&#x60;snapshot&#x60;** is exactly &#x60;GET /reports/occupancy?from&#x3D;date&amp;to&#x3D;date&#x60;&#39;s &#x60;total&#x60; row - the same computation, called, not reimplemented. 
     *
     * @param date The date to review (Asia/Bangkok). Defaults to today, hotel-local. (optional)
     * @return The checklist. (status code 200)
     *         or &#x60;date&#x60; is not a valid date. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/night-audit",
        produces = { "application/json" }
    )
    
    default ResponseEntity<NightAudit> getNightAudit(
        @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$")  @Valid @RequestParam(value = "date", required = false) String date
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"date\", \"missedArrivals\" : [ { \"roomUnitLabel\" : \"roomUnitLabel\", \"checkIn\" : \"checkIn\", \"occupancyStatus\" : \"EXPECTED\", \"id\" : \"id\", \"checkOut\" : \"checkOut\", \"roomName\" : \"roomName\", \"guestName\" : \"guestName\", \"status\" : \"NEW\" }, { \"roomUnitLabel\" : \"roomUnitLabel\", \"checkIn\" : \"checkIn\", \"occupancyStatus\" : \"EXPECTED\", \"id\" : \"id\", \"checkOut\" : \"checkOut\", \"roomName\" : \"roomName\", \"guestName\" : \"guestName\", \"status\" : \"NEW\" } ], \"missedDepartures\" : [ { \"roomUnitLabel\" : \"roomUnitLabel\", \"checkIn\" : \"checkIn\", \"occupancyStatus\" : \"EXPECTED\", \"id\" : \"id\", \"checkOut\" : \"checkOut\", \"roomName\" : \"roomName\", \"guestName\" : \"guestName\", \"status\" : \"NEW\" }, { \"roomUnitLabel\" : \"roomUnitLabel\", \"checkIn\" : \"checkIn\", \"occupancyStatus\" : \"EXPECTED\", \"id\" : \"id\", \"checkOut\" : \"checkOut\", \"roomName\" : \"roomName\", \"guestName\" : \"guestName\", \"status\" : \"NEW\" } ], \"closure\" : \"\", \"snapshot\" : { \"roomNightsSold\" : 5, \"revpar\" : \"revpar\", \"roomRevenue\" : \"roomRevenue\", \"roomNightsAvailable\" : 1, \"occupancyPercent\" : \"occupancyPercent\", \"roomId\" : \"roomId\", \"roomName\" : \"roomName\", \"adr\" : \"adr\", \"activeUnits\" : 6 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
