/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.CloseOrderInput;
import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.Order;
import com.sunsetbeach.model.OrderCreateInput;
import com.sunsetbeach.model.OrderItemInput;
import com.sunsetbeach.model.OrderStatus;
import com.sunsetbeach.model.OrderUpdateInput;
import com.sunsetbeach.model.SetRoomPricing400Response;
import com.sunsetbeach.model.ValidationError;
import com.sunsetbeach.model.Zone;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-07T19:32:58.716822+03:00[Europe/Moscow]", comments = "Generator version: 7.10.0")
@Validated
public interface OrdersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /orders/{id}/items : Add one or more line items to an order
     * Requires role &#x60;WAITER&#x60; or above. Legal while the order is &#x60;OPEN&#x60; or &#x60;SENT&#x60; - a guest adding a round of drinks after the order was already sent to the kitchen is normal, and appending new lines doesn&#39;t retroactively change anything about the lines already sent. &#x60;unitPrice&#x60; is snapshotted from the current &#x60;MenuItem.price&#x60; server-side — never taken from the client. Unlike this endpoint, &#x60;PATCH&#x60;/&#x60;DELETE&#x60; on an individual existing line (&#x60;/orders/{id}/items/{itemId}&#x60;) still require the order to be &#x60;OPEN&#x60; - editing or removing a line that may already be in progress in the kitchen is not offered here. Note there is no separate \&quot;sent to kitchen\&quot; timestamp: &#x60;Order.updatedAt&#x60; is overwritten by this call like any other mutation, so it cannot be used to tell which lines were on the original ticket versus added afterward - a kitchen-facing view would need to diff on &#x60;OrderItem.createdAt&#x60; for that. 
     *
     * @param id  (required)
     * @param orderItemInput  (required)
     * @return Updated order, with the new line(s) appended and &#x60;total&#x60; recomputed. (status code 201)
     *         or Body failed validation. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Order not found, or a &#x60;menuItemId&#x60; doesn&#39;t exist. (status code 404)
     *         or Order is not &#x60;OPEN&#x60; or &#x60;SENT&#x60; (i.e. it&#39;s already &#x60;PAID&#x60;/&#x60;CANCELLED&#x60;). (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/orders/{id}/items",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Order> addOrderItems(
         @PathVariable("id") String id,
         @Valid @RequestBody List<@Valid OrderItemInput> orderItemInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /orders/{id}/cancel : Cancel an order
     * Requires role &#x60;WAITER&#x60; or above. No payment is created.
     *
     * @param id  (required)
     * @return Cancelled order (status &#x60;CANCELLED&#x60;). (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Order not found. (status code 404)
     *         or Order already &#x60;PAID&#x60;/&#x60;CANCELLED&#x60;. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/orders/{id}/cancel",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Order> cancelOrder(
         @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /orders/{id}/close : Close an order with a payment
     * Requires role &#x60;CASHIER&#x60; or above, and requires the calling user to have an &#x60;OPEN&#x60; &#x60;Shift&#x60; (409 otherwise). Creates a &#x60;Payment&#x60; row for &#x60;Order.total&#x60;/&#x60;method&#x60; (and &#x60;bookingId&#x60; when &#x60;method&#x60; is &#x60;ROOM_CHARGE&#x60;) tied to that shift, then sets the order&#39;s status to &#x60;PAID&#x60;. The amount charged is always &#x60;Order.total&#x60; - see &#x60;CloseOrderInput&#x60;. 
     *
     * @param id  (required)
     * @param closeOrderInput  (required)
     * @return Closed order (status &#x60;PAID&#x60;). (status code 200)
     *         or Body failed validation, or &#x60;method&#x60; is &#x60;ROOM_CHARGE&#x60; without a &#x60;bookingId&#x60;. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or Order not found, or (for &#x60;ROOM_CHARGE&#x60;) &#x60;bookingId&#x60; not found. (status code 404)
     *         or Order already &#x60;PAID&#x60;/&#x60;CANCELLED&#x60;, caller has no open shift, or (for &#x60;ROOM_CHARGE&#x60;) the booking is &#x60;CANCELLED&#x60;. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/orders/{id}/close",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Order> closeOrder(
         @PathVariable("id") String id,
         @Valid @RequestBody CloseOrderInput closeOrderInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /orders : Open a new order
     * Requires role &#x60;WAITER&#x60; or above (i.e. any staff role — WAITER is the floor of the hierarchy).
     *
     * @param orderCreateInput  (required)
     * @return Order created with status &#x60;OPEN&#x60; and no items. (status code 201)
     *         or No valid JWT. (status code 401)
     *         or &#x60;tableId&#x60; or &#x60;bookingId&#x60; given but not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/orders",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Order> createOrder(
         @Valid @RequestBody OrderCreateInput orderCreateInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /orders/{id}/items/{itemId} : Remove a line item
     * Requires role &#x60;WAITER&#x60; or above. Only legal while the order is &#x60;OPEN&#x60;.
     *
     * @param id  (required)
     * @param itemId  (required)
     * @return Updated order, with &#x60;total&#x60; recomputed. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Order or line item not found. (status code 404)
     *         or Order is not &#x60;OPEN&#x60;. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/orders/{id}/items/{itemId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Order> deleteOrderItem(
         @PathVariable("id") String id,
         @PathVariable("itemId") String itemId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /orders/{id} : Get an order by id, with its line items
     * Requires any authenticated staff session.
     *
     * @param id  (required)
     * @return The order. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Order not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/orders/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Order> getOrder(
         @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /orders : List orders
     * Requires any authenticated staff session. Filters combine with AND.
     *
     * @param status  (optional)
     * @param zone Filters by the zone of the order&#39;s table; orders with no table never match. (optional)
     * @param tableId  (optional)
     * @param bookingId  (optional)
     * @return Matching orders. (status code 200)
     *         or No valid JWT. (status code 401)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/orders",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Order>> listOrders(
         @Valid @RequestParam(value = "status", required = false) OrderStatus status,
         @Valid @RequestParam(value = "zone", required = false) Zone zone,
         @Valid @RequestParam(value = "tableId", required = false) String tableId,
         @Valid @RequestParam(value = "bookingId", required = false) String bookingId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /orders/{id} : Update an order&#39;s note/table, or send it (OPEN -&gt; SENT)
     * Requires role &#x60;WAITER&#x60; or above.
     *
     * @param id  (required)
     * @param orderUpdateInput  (required)
     * @return Updated order. (status code 200)
     *         or Body failed validation, or &#x60;status&#x60; requested a transition other than &#x60;OPEN&#x60; -&gt; &#x60;SENT&#x60;. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Order not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/orders/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Order> updateOrder(
         @PathVariable("id") String id,
         @Valid @RequestBody OrderUpdateInput orderUpdateInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /orders/{id}/items/{itemId} : Replace a line item&#39;s quantity/note
     * Requires role &#x60;WAITER&#x60; or above. Only legal while the order is &#x60;OPEN&#x60;. &#x60;unitPrice&#x60; is not re-snapshotted.
     *
     * @param id  (required)
     * @param itemId  (required)
     * @param orderItemInput  (required)
     * @return Updated order, with &#x60;total&#x60; recomputed. (status code 200)
     *         or Body failed validation. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Order or line item not found. (status code 404)
     *         or Order is not &#x60;OPEN&#x60;. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/orders/{id}/items/{itemId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Order> updateOrderItem(
         @PathVariable("id") String id,
         @PathVariable("itemId") String itemId,
         @Valid @RequestBody OrderItemInput orderItemInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"total\" : \"total\", \"tableId\" : \"tableId\", \"openedByUserId\" : \"openedByUserId\", \"id\" : \"id\", \"items\" : [ { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" }, { \"unitPrice\" : \"unitPrice\", \"note\" : \"note\", \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"quantity\" : 0, \"orderId\" : \"orderId\", \"id\" : \"id\", \"menuItemId\" : \"menuItemId\" } ], \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"status\" : \"OPEN\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
