/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.PaymentsSummary;
import com.sunsetbeach.model.ValidationError;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-07T20:13:52.916230300+03:00[Europe/Moscow]", comments = "Generator version: 7.10.0")
@Validated
public interface PaymentsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /payments/summary : Get a payment totals summary for a date range
     * Requires role &#x60;MANAGER&#x60; or above. &#x60;from&#x60;/&#x60;to&#x60; are inclusive dates, filtered by &#x60;Payment.createdAt&#x60;. &#x60;totals&#x60; reuses the exact same per-method aggregation &#x60;GET /shifts/{id}&#x60; builds &#x60;ShiftSummary.totals&#x60; from - just scoped to a date range across all shifts instead of one shift (see &#x60;PaymentAggregation&#x60; in the backend; the arithmetic is not duplicated between the two).  **&#x60;totals.roomCharge&#x60; is not received revenue.** It&#39;s money moved onto a guest&#39;s room folio at the moment a POS order was closed with &#x60;method&#x3D;ROOM_CHARGE&#x60; - it only becomes real, collected revenue if/when the underlying &#x60;Booking&#x60; itself is later paid, which is a separate event this endpoint does not track (see &#x60;GET /bookings/{id}/folio&#x60;). Including it in a revenue total here would either double-count it (once here, again when the booking is paid) or count it before any money actually changed hands. &#x60;grandTotal&#x60; is therefore **&#x60;totals.cash + totals.card + totals.other&#x60; only** - &#x60;totals.roomCharge&#x60; is deliberately excluded and must be read as a separate \&quot;moved to room folios this period\&quot; figure, never added into &#x60;grandTotal&#x60; on the client. 
     *
     * @param from Inclusive start date (by &#x60;Payment.createdAt&#x60;). (required)
     * @param to Inclusive end date (by &#x60;Payment.createdAt&#x60;). (required)
     * @return Payment totals for the date range. (status code 200)
     *         or &#x60;from&#x60;/&#x60;to&#x60; missing, not a valid date, or &#x60;from&#x60; after &#x60;to&#x60;. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/payments/summary",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PaymentsSummary> getPaymentsSummary(
        @NotNull @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$")  @Valid @RequestParam(value = "from", required = true) String from,
        @NotNull @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$")  @Valid @RequestParam(value = "to", required = true) String to
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"grandTotal\" : \"grandTotal\", \"from\" : \"from\", \"to\" : \"to\", \"totals\" : { \"other\" : \"other\", \"roomCharge\" : \"roomCharge\", \"cash\" : \"cash\", \"paymentCount\" : 0, \"card\" : \"card\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
