/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.OkUpdated;
import com.sunsetbeach.model.PriceRangeInput;
import com.sunsetbeach.model.PricingResponse;
import com.sunsetbeach.model.SetRoomPricing400Response;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
public interface PricingApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /pricing/{roomId} : Get per-day prices for a room for a given month
     * Requires CASHIER or above - a CASHIER needs to quote a price to a walk-in guest through an authenticated endpoint rather than the public site (see &#x60;GET /rooms&#x60; for the same reasoning). Setting a price override (&#x60;PATCH&#x60;, below) stays MANAGER-only. Part of the same deliberate combined cashier/front-desk role scoping - see &#x60;POST /bookings/staff&#x60;&#39;s description for the full reasoning. 
     *
     * @param roomId  (required)
     * @param month Month key &#x60;YYYY-MM&#x60;. Defaults to the current UTC month. (optional)
     * @return Base price and the resolved price for every day of the month. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Room not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/pricing/{roomId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<PricingResponse> getRoomPricing(
         @PathVariable("roomId") String roomId,
        @Pattern(regexp = "^\\d{4}-\\d{2}$")  @Valid @RequestParam(value = "month", required = false) String month
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"days\" : [ { \"date\" : \"date\", \"price\" : 6.027456183070403, \"isOverride\" : true }, { \"date\" : \"date\", \"price\" : 6.027456183070403, \"isOverride\" : true } ], \"basePrice\" : 0.8008281904610115 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /pricing/{roomId} : Set a price override for a date range
     * Requires any authenticated staff session (ADMIN or MANAGER). Upserts one &#x60;RatePlan&#x60; row per day in &#x60;[from, to]&#x60; (inclusive). Rejects ranges longer than 366 days. 
     *
     * @param roomId  (required)
     * @param priceRangeInput  (required)
     * @return Number of days upserted. (status code 200)
     *         or Body failed &#x60;priceRangeSchema&#x60; validation, or the range exceeds 366 days. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Room not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/pricing/{roomId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<OkUpdated> setRoomPricing(
         @PathVariable("roomId") String roomId,
         @Valid @RequestBody PriceRangeInput priceRangeInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ok\" : true, \"updated\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : { \"formErrors\" : [ ], \"fieldErrors\" : { \"guestEmail\" : [ \"Invalid email\" ] } } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
