/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import org.springframework.format.annotation.DateTimeFormat;
import com.sunsetbeach.model.ErrorMessage;
import java.time.LocalDate;
import com.sunsetbeach.model.Shift;
import com.sunsetbeach.model.ShiftCloseInput;
import com.sunsetbeach.model.ShiftListItem;
import com.sunsetbeach.model.ShiftOpenInput;
import com.sunsetbeach.model.ShiftSummary;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
public interface ShiftsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /shifts/{id}/close : Close a shift
     * Requires role &#x60;CASHIER&#x60; or above.
     *
     * @param id  (required)
     * @param shiftCloseInput  (required)
     * @return Closed shift (status &#x60;CLOSED&#x60;). (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or Shift not found. (status code 404)
     *         or Already &#x60;CLOSED&#x60;, or there are &#x60;OPEN&#x60;/&#x60;SENT&#x60; orders anywhere in the system. This is a system-wide gate, not scoped to this particular shift - &#x60;Order&#x60; has no &#x60;shiftId&#x60; (only &#x60;Payment&#x60; does, and only once an order is closed), so there is no way to ask \&quot;orders opened during this shift\&quot; and the check intentionally doesn&#39;t pretend otherwise.  (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/shifts/{id}/close",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Shift> closeShift(
         @PathVariable("id") String id,
         @Valid @RequestBody ShiftCloseInput shiftCloseInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : \"notes\", \"openingCashFloat\" : \"openingCashFloat\", \"openedByUserId\" : \"openedByUserId\", \"closedByUserId\" : \"closedByUserId\", \"id\" : \"id\", \"closedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"closingCashCounted\" : \"closingCashCounted\", \"openedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"OPEN\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /shifts/{id}/export : Export a shift&#39;s Z-report as CSV
     * Requires role &#x60;MANAGER&#x60; or above. This is the till-reconciliation report, not a raw payment dump: identifiers that only make sense to a database (order/booking/cashier UUIDs) are replaced with what a manager actually needs to read - the order&#39;s table/zone and item composition (or a short fallback if there&#39;s no table), the guest name and room for ROOM_CHARGE payments, and the cashier&#39;s email. The underlying &#x60;Payment.id&#x60;/&#x60;Order.id&#x60; are kept as the last two columns for support/audit lookups, not as the first thing a human sees. Timestamps are seconds-precision (&#x60;yyyy-MM-dd HH:mm:ss \&quot;UTC\&quot;&#x60;), not the millisecond ISO instant used elsewhere in the API.  The file opens with a UTF-8 BOM and a &#x60;sep&#x3D;,&#x60; directive line - see &#x60;GET /bookings/export&#x60;&#39;s description for why.  After the payment rows, a blank line separates a totals block (label, value per row): &#x60;Cash&#x60;/&#x60;Card&#x60;/&#x60;Other&#x60;/&#x60;Room charge (posted to room folio - not received cash/card)&#x60; (same per-method split and the same ROOM_CHARGE exclusion as &#x60;GET /payments/summary&#x60; - see that operation&#39;s description for why ROOM_CHARGE isn&#39;t received revenue), &#x60;Received total (cash + card + other)&#x60;, &#x60;Payments&#x60; (count), &#x60;Opening cash float&#x60;, &#x60;Expected cash (float + cash payments)&#x60;, &#x60;Counted cash&#x60; (the shift&#39;s &#x60;closingCashCounted&#x60;, or &#x60;—&#x60; if the shift hasn&#39;t been closed/recounted yet), and finally &#x60;Discrepancy (counted - expected)&#x60; - positive means the drawer has more cash than it should, negative means it&#39;s short. This last figure is the actual point of closing a shift. 
     *
     * @param id  (required)
     * @return CSV file: a header row, one row per payment recorded under this shift, a blank row, then the reconciliation totals block described above.  (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     *         or Shift not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/shifts/{id}/export",
        produces = { "text/csv", "application/json" }
    )
    
    default ResponseEntity<String> exportShift(
         @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf(""))) {
                    String exampleString = "";
                    ApiUtil.setExampleResponse(request, "", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /shifts/current : Get the calling user&#39;s currently open shift
     * Requires role &#x60;CASHIER&#x60; or above. Looks up by &#x60;openedByUserId&#x60; &#x3D; the calling user&#39;s id AND &#x60;status&#x3D;OPEN&#x60; - never returns another user&#39;s shift, even to a MANAGER/ADMIN caller. Lets a client on any device discover whether it already has an open shift without relying on browser local storage. 
     *
     * @return The calling user&#39;s open shift. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or The calling user has no open shift. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/shifts/current",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Shift> getCurrentShift(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : \"notes\", \"openingCashFloat\" : \"openingCashFloat\", \"openedByUserId\" : \"openedByUserId\", \"closedByUserId\" : \"closedByUserId\", \"id\" : \"id\", \"closedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"closingCashCounted\" : \"closingCashCounted\", \"openedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"OPEN\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /shifts/{id} : Get a shift summary
     * Requires role &#x60;CASHIER&#x60; or above. A caller whose role is exactly &#x60;CASHIER&#x60; (not &#x60;MANAGER&#x60;/&#x60;ADMIN&#x60;) may only fetch a shift they themselves opened - any other shift id 404s for them, same as if it didn&#39;t exist, to avoid confirming another cashier&#39;s shift even exists. &#x60;MANAGER&#x60;/&#x60;ADMIN&#x60; can fetch any shift. 
     *
     * @param id  (required)
     * @return The shift with payment totals broken out by method. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or Shift not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/shifts/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<ShiftSummary> getShift(
         @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : \"notes\", \"openingCashFloat\" : \"openingCashFloat\", \"openedByUserId\" : \"openedByUserId\", \"closedByUserId\" : \"closedByUserId\", \"id\" : \"id\", \"totals\" : { \"other\" : \"other\", \"roomCharge\" : \"roomCharge\", \"cash\" : \"cash\", \"paymentCount\" : 0, \"card\" : \"card\" }, \"closedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"closingCashCounted\" : \"closingCashCounted\", \"openedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"OPEN\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /shifts : List shifts for till reconciliation review
     * Requires role &#x60;MANAGER&#x60; or above. One row per shift, reconciliation numbers (&#x60;expectedCash&#x60;/&#x60;discrepancy&#x60;) already computed - previously the only way to see this across more than one shift was paging through the general audit log for &#x60;SHIFT_CLOSED&#x60; entries and reading the discrepancy back out of free text. &#x60;GET /shifts/{id}/export&#x60; is the single-shift CSV detail underneath this; this operation is what points a manager at *which* shift needs a closer look, or export, next.  &#x60;from&#x60;/&#x60;to&#x60; bound &#x60;openedAt&#x60; (closed on both ends, matching every other date-range filter in this API), &#x60;staffId&#x60; narrows to shifts opened by one user. All filters are optional; with none given, every shift ever opened comes back, newest first, so a full audit doesn&#39;t require guessing a date range first. 
     *
     * @param from  (optional)
     * @param to  (optional)
     * @param staffId  (optional)
     * @return Shifts matching the filters, newest first. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;MANAGER&#x60; or above). (status code 403)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/shifts",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<ShiftListItem>> listShifts(
         @Valid @RequestParam(value = "from", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate from,
         @Valid @RequestParam(value = "to", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate to,
         @Valid @RequestParam(value = "staffId", required = false) String staffId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"expectedCash\" : \"expectedCash\", \"openedByEmail\" : \"openedByEmail\", \"totals\" : { \"other\" : \"other\", \"roomCharge\" : \"roomCharge\", \"cash\" : \"cash\", \"paymentCount\" : 0, \"card\" : \"card\" }, \"openedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"discrepancy\" : \"discrepancy\", \"closedByEmail\" : \"closedByEmail\", \"openingCashFloat\" : \"openingCashFloat\", \"openedByUserId\" : \"openedByUserId\", \"closedByUserId\" : \"closedByUserId\", \"id\" : \"id\", \"closedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"closingCashCounted\" : \"closingCashCounted\", \"status\" : \"OPEN\" }, { \"expectedCash\" : \"expectedCash\", \"openedByEmail\" : \"openedByEmail\", \"totals\" : { \"other\" : \"other\", \"roomCharge\" : \"roomCharge\", \"cash\" : \"cash\", \"paymentCount\" : 0, \"card\" : \"card\" }, \"openedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"discrepancy\" : \"discrepancy\", \"closedByEmail\" : \"closedByEmail\", \"openingCashFloat\" : \"openingCashFloat\", \"openedByUserId\" : \"openedByUserId\", \"closedByUserId\" : \"closedByUserId\", \"id\" : \"id\", \"closedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"closingCashCounted\" : \"closingCashCounted\", \"status\" : \"OPEN\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /shifts/open : Open a shift for the calling user
     * Requires role &#x60;CASHIER&#x60; or above. 409 if the calling user already has an open shift (enforced by a unique partial index, not just an application-level check).
     *
     * @param shiftOpenInput  (required)
     * @return Shift opened. (status code 201)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or Caller already has an open shift. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/shifts/open",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Shift> openShift(
         @Valid @RequestBody ShiftOpenInput shiftOpenInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : \"notes\", \"openingCashFloat\" : \"openingCashFloat\", \"openedByUserId\" : \"openedByUserId\", \"closedByUserId\" : \"closedByUserId\", \"id\" : \"id\", \"closedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"closingCashCounted\" : \"closingCashCounted\", \"openedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"OPEN\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
