/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.sunsetbeach.api;

import com.sunsetbeach.model.ErrorMessage;
import com.sunsetbeach.model.SpaAppointment;
import com.sunsetbeach.model.SpaAppointmentCreateInput;
import com.sunsetbeach.model.SpaAppointmentResult;
import com.sunsetbeach.model.SpaAppointmentStatusUpdateInput;
import com.sunsetbeach.model.SpaSchedule;
import com.sunsetbeach.model.SpaTherapist;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0")
@Validated
public interface SpaApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /spa-appointments : Book a spa appointment
     * Requires CASHIER or above. Both the table and the therapist must be free for the whole slot - enforced by a database exclusion constraint on each axis, not a check-then-write; a genuine race (two receptionists booking the same therapist at once) surfaces as 409 on whichever request loses, not a 500 or a silent double-booking. 
     *
     * @param spaAppointmentCreateInput  (required)
     * @return Appointment created (possibly with a warning - see &#x60;SpaAppointmentResult&#x60;). (status code 201)
     *         or Body failed validation, &#x60;treatmentMenuItemId&#x60; isn&#39;t a &#x60;SPA&#x60;-department item with a duration, or &#x60;startTime&#x60; falls outside opening hours / off the half-hour grid. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or bookingId, tableId, therapistUserId, or treatmentMenuItemId does not reference an existing row. (status code 404)
     *         or The table or the therapist already has an overlapping BOOKED appointment. (status code 409)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/spa-appointments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SpaAppointmentResult> createSpaAppointment(
         @Valid @RequestBody SpaAppointmentCreateInput spaAppointmentCreateInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"warning\" : \"warning\", \"appointment\" : { \"date\" : \"date\", \"createdByUserId\" : \"createdByUserId\", \"orderId\" : \"orderId\", \"therapistEmail\" : \"therapistEmail\", \"treatmentMenuItemId\" : \"treatmentMenuItemId\", \"cancelledByUserId\" : \"cancelledByUserId\", \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"durationMinutes\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"therapistUserId\" : \"therapistUserId\", \"tableId\" : \"tableId\", \"tableLabel\" : \"tableLabel\", \"startTime\" : \"startTime\", \"id\" : \"id\", \"cancelReason\" : \"cancelReason\", \"treatmentName\" : \"treatmentName\", \"status\" : \"BOOKED\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /spa-appointments : Get the spa&#39;s half-hour grid for one day
     * Requires CASHIER or above. &#x60;tables&#x60; (SPA-zone) and &#x60;appointments&#x60; for &#x60;date&#x60;, plus the backend&#39;s own opening hours - see &#x60;SpaSchedule&#x60;.
     *
     * @param date  (required)
     * @return The spa&#39;s schedule for the day. (status code 200)
     *         or &#x60;date&#x60; missing or not &#x60;YYYY-MM-DD&#x60;. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/spa-appointments",
        produces = { "application/json" }
    )
    
    default ResponseEntity<SpaSchedule> getSpaSchedule(
        @NotNull @Pattern(regexp = "^\\d{4}-\\d{2}-\\d{2}$")  @Valid @RequestParam(value = "date", required = true) String date
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"date\", \"tables\" : [ { \"positionY\" : 0.14658129805029452, \"zone\" : \"RESTAURANT\", \"id\" : \"id\", \"label\" : \"label\", \"isActive\" : true, \"capacity\" : 0, \"positionX\" : 0.6027456183070403 }, { \"positionY\" : 0.14658129805029452, \"zone\" : \"RESTAURANT\", \"id\" : \"id\", \"label\" : \"label\", \"isActive\" : true, \"capacity\" : 0, \"positionX\" : 0.6027456183070403 } ], \"appointments\" : [ { \"date\" : \"date\", \"createdByUserId\" : \"createdByUserId\", \"orderId\" : \"orderId\", \"therapistEmail\" : \"therapistEmail\", \"treatmentMenuItemId\" : \"treatmentMenuItemId\", \"cancelledByUserId\" : \"cancelledByUserId\", \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"durationMinutes\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"therapistUserId\" : \"therapistUserId\", \"tableId\" : \"tableId\", \"tableLabel\" : \"tableLabel\", \"startTime\" : \"startTime\", \"id\" : \"id\", \"cancelReason\" : \"cancelReason\", \"treatmentName\" : \"treatmentName\", \"status\" : \"BOOKED\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"date\" : \"date\", \"createdByUserId\" : \"createdByUserId\", \"orderId\" : \"orderId\", \"therapistEmail\" : \"therapistEmail\", \"treatmentMenuItemId\" : \"treatmentMenuItemId\", \"cancelledByUserId\" : \"cancelledByUserId\", \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"durationMinutes\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"therapistUserId\" : \"therapistUserId\", \"tableId\" : \"tableId\", \"tableLabel\" : \"tableLabel\", \"startTime\" : \"startTime\", \"id\" : \"id\", \"cancelReason\" : \"cancelReason\", \"treatmentName\" : \"treatmentName\", \"status\" : \"BOOKED\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ], \"closingTime\" : \"closingTime\", \"openingTime\" : \"openingTime\", \"slotMinutes\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /spa-appointments/therapists : List active staff holding the THERAPIST job function
     * Requires CASHIER or above - see &#x60;SpaTherapist&#x60; for why this is narrower than &#x60;GET /users&#x60;.
     *
     * @return Active therapists. (status code 200)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/spa-appointments/therapists",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<SpaTherapist>> listSpaTherapists(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"id\" : \"id\", \"email\" : \"email\" }, { \"id\" : \"id\", \"email\" : \"email\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /spa-appointments/{id}/status : Cancel, mark no-show, or complete a spa appointment
     * Requires CASHIER or above. No therapist self-service in v1 - no therapist is signing into this system yet, see &#x60;JobFunction.THERAPIST&#x60;. &#x60;COMPLETED&#x60; is never set automatically by an order closing - the two lifecycles are deliberately independent, see &#x60;SpaAppointment.orderId&#x60;. 
     *
     * @param id  (required)
     * @param spaAppointmentStatusUpdateInput  (required)
     * @return Updated appointment. (status code 200)
     *         or &#x60;status&#x60; is &#x60;BOOKED&#x60;, or the appointment is already in an end state. (status code 400)
     *         or No valid JWT. (status code 401)
     *         or Token is valid but lacks the required role (&#x60;CASHIER&#x60; or above). (status code 403)
     *         or Appointment not found. (status code 404)
     */
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/spa-appointments/{id}/status",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<SpaAppointment> updateSpaAppointmentStatus(
         @PathVariable("id") String id,
         @Valid @RequestBody SpaAppointmentStatusUpdateInput spaAppointmentStatusUpdateInput
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"date\", \"createdByUserId\" : \"createdByUserId\", \"orderId\" : \"orderId\", \"therapistEmail\" : \"therapistEmail\", \"treatmentMenuItemId\" : \"treatmentMenuItemId\", \"cancelledByUserId\" : \"cancelledByUserId\", \"bookingId\" : \"bookingId\", \"guestName\" : \"guestName\", \"durationMinutes\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"therapistUserId\" : \"therapistUserId\", \"tableId\" : \"tableId\", \"tableLabel\" : \"tableLabel\", \"startTime\" : \"startTime\", \"id\" : \"id\", \"cancelReason\" : \"cancelReason\", \"treatmentName\" : \"treatmentName\", \"status\" : \"BOOKED\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"error\" : \"error\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
