ALTER TYPE "AuditAction" ADD VALUE 'ROSTER_ENTRY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ROSTER_ENTRY_MOVED';
ALTER TYPE "AuditAction" ADD VALUE 'ROSTER_ENTRY_REASSIGNED';
ALTER TYPE "AuditAction" ADD VALUE 'ROSTER_ENTRIES_SWAPPED';
ALTER TYPE "AuditAction" ADD VALUE 'ROSTER_ENTRY_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'ROSTER_ENTRY_LOCKED_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'ROSTER_MONTH_GENERATED';
ALTER TYPE "AuditEntityType" ADD VALUE 'ROSTER_ENTRY';
